runtime: python39
entrypoint: gunicorn -b :$PORT KookminHospital.wsgi:application

env_variables:
  DJANGO_SETTINGS_MODULE: "KookminHospital.settings"

handlers:
- url: /static
  static_dir: static/
- url: /.*
  script: auto
