# Generated by Django 4.2.13 on 2024-05-18 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_drug_id_alter_patient_id'),
        ('nurse', '0002_alter_nurse_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hospital.patient'),
            preserve_default=False,
        ),
    ]
